export default {
    LOGIN: 'LOGIN',
    USER: 'USER',
    AVATARS: 'AVATARS',


    // GAMES
    MY_GAMES: 'MY_GAMES',
    LOADING_MY_GAMES: 'LOADING_MY_GAMES',

    GAMES: 'GAMES',
    LOADING_GAMES: 'LOADING_GAMES',
    GAME_FILTER: 'GAME_FILTER',

    // SORTEO
    SORTEO: 'SORTEO',
    LOADING_SORTEO: 'LOADING_SORTEO',
    
    // JUEGOS SUSCRITOS.
    SUBSCRIBED: 'SUBSCRIBED',
    LOADING_SUBSCRIBED: 'LOADING_SUBSCRIBED',

    // OBTENER DATOS DEL JUEGO PARA WINNER
    WINNER_GAME: 'WINNER_GAME',
    LOADING_WINNER: "LOADING_WINNER",

    // TIQUETES
    TICKET: 'TICKET',
    LOADING_TICKET: 'LOADING_TICKET',

    // PROFILE
    PROFILE: 'PROFILE',
    LOADING_PROFILE: 'LOADING_PROFILE'
} 